### ISSUE TITLE
Install on CentOS and Fedora x86_64

### ISSUE THREAD

**Issue by f0rb1dd3n** [zephrax/linux-pam-backdoor#1]
Hello man, how are you?

I was testing this kind of approach to backdoor PAM on RHEL based systems x86_64.

So I didn't get success. I searched the right PAM version with this command:

`yum list pam | grep @ | cut -d " " -f 25 | cut -d "-" -f 1`

and after that, I have downloaded the same version of PAM, patched, compiled and installed on the following directory: `/usr/lib64/security`.

The /usr/lib/security doesnt exsists on this system, and I have searched for this folder with: `find / -name pam_unix.so`

Then, after that, I cant connect on the SSH with the right magic password and even with the real password. The authenticate module is broken now. (obviously I have a backup).

So can you help me a mitigate this error?

Thanks for your time.

**Comment by f0rb1dd3n** [comment]
Hello man sorry about hurry you. I figured it out just installing these dependencies:

`yum install nss-devel nspr-devel libevent-devel unbound-devel pam-devel audit-libs-devel libcurl-devel libseccomp-devel systemd-devel libcap-ng-devel fipscheck-devel ldns-devel xmlto`

sorry for opening this issue, but I have tried a lot and I didnt know how to figure out.

Thanks your patience

**Comment by segmentati0nf4ult** [comment]
Hi man, no problem. We are here to share code & knowledge. For any quick question you can always find me on irc.kernelpanic.com.ar

**Comment by f0rb1dd3n** [comment]
Thanks man, I will connect there later. I will write a PAM backdoor on Solaris too. Maybe we can talk about ;)
